config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'login' => 'users#login'

  get 'find_friends' => 'users#find_friends'
  
  get 'roll_calls/show_group' => 'roll_calls#show_group'

  resources :likes

  resources :photos

  resources :roll_calls

  resources :memberships

  resources :groups

  resources :users

end

app/models/roll_call.rb
class RollCall < ActiveRecord::Base
  belongs_to    :user
  belongs_to    :group
  has_many      :selfies 

  validates :group, presence: true
  validates :user, presence: true
end

app/controllers/roll_calls_controller.rb
class RollCallsController < ApplicationController
  before_action :set_roll_call, only: [:show, :edit, :update, :destroy]

  before_action :restrict_access

  # GET /roll_calls
  # GET /roll_calls.json
  def index
    @groups = @current_user.groups
    @roll_calls = []
    @groups.each do |g|
      g.roll_calls.each do |r|
        @roll_calls << r
      end
    end
  end

  def show_group
    @group = Group.find(params[:group_id])
    @roll_calls = @group.roll_calls
    render json: @roll_calls
  end

  # GET /roll_calls/1
  # GET /roll_calls/1.json
  def show
  end

  # GET /roll_calls/new
  def new
    @roll_call = RollCall.new
  end

  # GET /roll_calls/1/edit
  def edit
  end

  # POST /roll_calls
  # POST /roll_calls.json
  def create
    @roll_call = RollCall.new(roll_call_params)
    @roll_call.user = @current_user
    @roll_call.started = Time.now

    respond_to do |format|
      if @roll_call.save
        format.json { render :show, status: :created, location: @roll_call }
      else
        format.json { render json: @roll_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roll_calls/1
  # PATCH/PUT /roll_calls/1.json
  def update
    respond_to do |format|
      if @roll_call.update(roll_call_params)
        format.json { render :show, status: :ok, location: @roll_call }
      else
        format.json { render json: @roll_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roll_calls/1
  # DELETE /roll_calls/1.json
  def destroy
    @roll_call.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roll_call
      @roll_call = RollCall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roll_call_params
      params.require(:roll_call).permit(:started, :ended, :duration, :description, :group_id, :user_id)
    end
end

app/helpers/roll_calls_helper.rb
module RollCallsHelper
end

app/views/roll_calls/_form.html.erb
<%= form_for(@roll_call) do |f| %>
  <% if @roll_call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roll_call.errors.count, "error") %> prohibited this roll_call from being saved:</h2>

      <ul>
      <% @roll_call.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :started %><br>
    <%= f.datetime_select :started %>
  </div>
  <div class="field">
    <%= f.label :ended %><br>
    <%= f.datetime_select :ended %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roll_calls/edit.html.erb
<h1>Editing roll_call</h1>

<%= render 'form' %>

<%= link_to 'Show', @roll_call %> |
<%= link_to 'Back', roll_calls_path %>

app/views/roll_calls/index.html.erb
<h1>Listing roll_calls</h1>

<table>
  <thead>
    <tr>
      <th>Started</th>
      <th>Ended</th>
      <th>Duration</th>
      <th>Description</th>
      <th>Group</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roll_calls.each do |roll_call| %>
      <tr>
        <td><%= roll_call.started %></td>
        <td><%= roll_call.ended %></td>
        <td><%= roll_call.duration %></td>
        <td><%= roll_call.description %></td>
        <td><%= roll_call.group_id %></td>
        <td><%= roll_call.user_id %></td>
        <td><%= link_to 'Show', roll_call %></td>
        <td><%= link_to 'Edit', edit_roll_call_path(roll_call) %></td>
        <td><%= link_to 'Destroy', roll_call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roll call', new_roll_call_path %>

app/views/roll_calls/new.html.erb
<h1>New roll_call</h1>

<%= render 'form' %>

<%= link_to 'Back', roll_calls_path %>

app/views/roll_calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Started:</strong>
  <%= @roll_call.started %>
</p>

<p>
  <strong>Ended:</strong>
  <%= @roll_call.ended %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @roll_call.duration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @roll_call.description %>
</p>

<p>
  <strong>Group:</strong>
  <%= @roll_call.group_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @roll_call.user_id %>
</p>

<%= link_to 'Edit', edit_roll_call_path(@roll_call) %> |
<%= link_to 'Back', roll_calls_path %>